name: commuter-dev

services:
  commuter:
    build: .
    environment:
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
    networks:
      - web
      - default
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.commuter-dev.entrypoints: "web"
      traefik.http.routers.commuter-dev.rule: "Host(`commuter-dev.dbut.dev`)"
      traefik.http.services.commuter-dev.loadbalancer.server.port: "8080"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:alpine
    hostname: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:

networks:
  web:
    external: true
