// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const getActivity = `-- name: GetActivity :one
select id, user_id, strava_id, status, applied_rules, activity_time, created_at, updated_at from activities where id = $1 and user_id = $2
`

type GetActivityParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetActivity(ctx context.Context, arg GetActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, getActivity, arg.ID, arg.UserID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StravaID,
		&i.Status,
		&i.AppliedRules,
		&i.ActivityTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFeed = `-- name: ListFeed :many
select
    a.id, a.user_id, a.strava_id, a.status, a.applied_rules, a.activity_time, a.created_at, a.updated_at,
    sd.data as strava_data,
    j.status as job_status,
    j.next_run as job_next_run,
    j.expires_at as job_expires_at
from activities a
left join provider_data sd on sd.activity_id = a.id and sd.provider = 'strava'
left join jobs j on j.activity_id = a.id
where a.user_id = $1
order by a.activity_time desc nulls last, a.created_at desc
`

type ListFeedRow struct {
	ID           uuid.UUID             `json:"id"`
	UserID       uuid.UUID             `json:"user_id"`
	StravaID     int64                 `json:"strava_id"`
	Status       string                `json:"status"`
	AppliedRules json.RawMessage       `json:"applied_rules"`
	ActivityTime sql.NullTime          `json:"activity_time"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
	StravaData   pqtype.NullRawMessage `json:"strava_data"`
	JobStatus    sql.NullString        `json:"job_status"`
	JobNextRun   sql.NullTime          `json:"job_next_run"`
	JobExpiresAt sql.NullTime          `json:"job_expires_at"`
}

func (q *Queries) ListFeed(ctx context.Context, userID uuid.UUID) ([]ListFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedRow
	for rows.Next() {
		var i ListFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StravaID,
			&i.Status,
			&i.AppliedRules,
			&i.ActivityTime,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StravaData,
			&i.JobStatus,
			&i.JobNextRun,
			&i.JobExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setActivityStatus = `-- name: SetActivityStatus :exec
update activities set status = $2, updated_at = now() where id = $1
`

type SetActivityStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetActivityStatus(ctx context.Context, arg SetActivityStatusParams) error {
	_, err := q.db.ExecContext(ctx, setActivityStatus, arg.ID, arg.Status)
	return err
}

const upsertActivity = `-- name: UpsertActivity :one
insert into activities (user_id, strava_id, status, applied_rules, activity_time)
values ($1, $2, $3, $4, $5)
on conflict (strava_id) do update
set status = excluded.status,
    applied_rules = excluded.applied_rules,
    activity_time = coalesce(excluded.activity_time, activities.activity_time),
    updated_at = now()
returning id, user_id, strava_id, status, applied_rules, activity_time, created_at, updated_at
`

type UpsertActivityParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	StravaID     int64           `json:"strava_id"`
	Status       string          `json:"status"`
	AppliedRules json.RawMessage `json:"applied_rules"`
	ActivityTime sql.NullTime    `json:"activity_time"`
}

func (q *Queries) UpsertActivity(ctx context.Context, arg UpsertActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, upsertActivity,
		arg.UserID,
		arg.StravaID,
		arg.Status,
		arg.AppliedRules,
		arg.ActivityTime,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StravaID,
		&i.Status,
		&i.AppliedRules,
		&i.ActivityTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
