// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const claimJobs = `-- name: ClaimJobs :many
select j.activity_id, a.user_id, a.strava_id, j.expires_at
from jobs j
join activities a on a.id = j.activity_id
where j.status = 'queued' and j.next_run <= now()
order by j.next_run
limit $1
`

type ClaimJobsRow struct {
	ActivityID uuid.UUID `json:"activity_id"`
	UserID     uuid.UUID `json:"user_id"`
	StravaID   int64     `json:"strava_id"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) ClaimJobs(ctx context.Context, limit int32) ([]ClaimJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, claimJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimJobsRow
	for rows.Next() {
		var i ClaimJobsRow
		if err := rows.Scan(
			&i.ActivityID,
			&i.UserID,
			&i.StravaID,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeJob = `-- name: CompleteJob :exec
update jobs set status = $2, last_error = $3, updated_at = now() where activity_id = $1
`

type CompleteJobParams struct {
	ActivityID uuid.UUID      `json:"activity_id"`
	Status     string         `json:"status"`
	LastError  sql.NullString `json:"last_error"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.ActivityID, arg.Status, arg.LastError)
	return err
}

const getJob = `-- name: GetJob :one
select id, activity_id, status, next_run, expires_at, last_error, created_at, updated_at from jobs where activity_id = $1
`

func (q *Queries) GetJob(ctx context.Context, activityID uuid.UUID) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, activityID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.Status,
		&i.NextRun,
		&i.ExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertJob = `-- name: UpsertJob :exec
insert into jobs (activity_id, status, next_run, expires_at)
values ($1, 'queued', $2, $3)
on conflict (activity_id) do update
set status = 'queued', next_run = excluded.next_run, expires_at = excluded.expires_at, updated_at = now()
`

type UpsertJobParams struct {
	ActivityID uuid.UUID `json:"activity_id"`
	NextRun    time.Time `json:"next_run"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.ExecContext(ctx, upsertJob, arg.ActivityID, arg.NextRun, arg.ExpiresAt)
	return err
}
