// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Activity struct {
	ID           uuid.UUID       `json:"id"`
	UserID       uuid.UUID       `json:"user_id"`
	StravaID     int64           `json:"strava_id"`
	Status       string          `json:"status"`
	AppliedRules json.RawMessage `json:"applied_rules"`
	ActivityTime sql.NullTime    `json:"activity_time"`
	CreatedAt    time.Time       `json:"created_at"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type Job struct {
	ID         uuid.UUID      `json:"id"`
	ActivityID uuid.UUID      `json:"activity_id"`
	Status     string         `json:"status"`
	NextRun    time.Time      `json:"next_run"`
	ExpiresAt  time.Time      `json:"expires_at"`
	LastError  sql.NullString `json:"last_error"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type ProviderDatum struct {
	ActivityID uuid.UUID       `json:"activity_id"`
	Provider   string          `json:"provider"`
	Data       json.RawMessage `json:"data"`
	Found      bool            `json:"found"`
	FetchedAt  time.Time       `json:"fetched_at"`
}

type Rule struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	Name       string          `json:"name"`
	Enabled    bool            `json:"enabled"`
	Priority   int32           `json:"priority"`
	Conditions json.RawMessage `json:"conditions"`
	Actions    json.RawMessage `json:"actions"`
	CreatedAt  time.Time       `json:"created_at"`
	UpdatedAt  time.Time       `json:"updated_at"`
}

type StravaCredential struct {
	UserID    uuid.UUID       `json:"user_id"`
	Token     json.RawMessage `json:"token"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type User struct {
	ID              uuid.UUID      `json:"id"`
	StravaAthleteID int64          `json:"strava_athlete_id"`
	Name            string         `json:"name"`
	ParkrunID       sql.NullString `json:"parkrun_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
