// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_data.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getProviderData = `-- name: GetProviderData :one
select data, found from provider_data where activity_id = $1 and provider = $2
`

type GetProviderDataParams struct {
	ActivityID uuid.UUID `json:"activity_id"`
	Provider   string    `json:"provider"`
}

type GetProviderDataRow struct {
	Data  json.RawMessage `json:"data"`
	Found bool            `json:"found"`
}

func (q *Queries) GetProviderData(ctx context.Context, arg GetProviderDataParams) (GetProviderDataRow, error) {
	row := q.db.QueryRowContext(ctx, getProviderData, arg.ActivityID, arg.Provider)
	var i GetProviderDataRow
	err := row.Scan(&i.Data, &i.Found)
	return i, err
}

const listProviderData = `-- name: ListProviderData :many
select activity_id, provider, data, found, fetched_at from provider_data where activity_id = $1 order by provider
`

func (q *Queries) ListProviderData(ctx context.Context, activityID uuid.UUID) ([]ProviderDatum, error) {
	rows, err := q.db.QueryContext(ctx, listProviderData, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderDatum
	for rows.Next() {
		var i ProviderDatum
		if err := rows.Scan(
			&i.ActivityID,
			&i.Provider,
			&i.Data,
			&i.Found,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderData = `-- name: UpsertProviderData :exec
insert into provider_data (activity_id, provider, data, found)
values ($1, $2, $3, $4)
on conflict (activity_id, provider) do update
set data = excluded.data, found = excluded.found, fetched_at = now()
`

type UpsertProviderDataParams struct {
	ActivityID uuid.UUID       `json:"activity_id"`
	Provider   string          `json:"provider"`
	Data       json.RawMessage `json:"data"`
	Found      bool            `json:"found"`
}

func (q *Queries) UpsertProviderData(ctx context.Context, arg UpsertProviderDataParams) error {
	_, err := q.db.ExecContext(ctx, upsertProviderData,
		arg.ActivityID,
		arg.Provider,
		arg.Data,
		arg.Found,
	)
	return err
}
