// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rules.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countRules = `-- name: CountRules :one
select count(*) from rules where user_id = $1
`

func (q *Queries) CountRules(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRules, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRule = `-- name: CreateRule :one
insert into rules (user_id, name, enabled, priority, conditions, actions)
values (
    $1,
    $2,
    true,
    coalesce((select max(priority) + 1 from rules where user_id = $1), 0),
    $3,
    $4
)
returning id, user_id, name, enabled, priority, conditions, actions, created_at, updated_at
`

type CreateRuleParams struct {
	UserID     uuid.UUID       `json:"user_id"`
	Name       string          `json:"name"`
	Conditions json.RawMessage `json:"conditions"`
	Actions    json.RawMessage `json:"actions"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, createRule,
		arg.UserID,
		arg.Name,
		arg.Conditions,
		arg.Actions,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.Conditions,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
delete from rules where id = $1 and user_id = $2
`

type DeleteRuleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteRule(ctx context.Context, arg DeleteRuleParams) error {
	_, err := q.db.ExecContext(ctx, deleteRule, arg.ID, arg.UserID)
	return err
}

const getRule = `-- name: GetRule :one
select id, user_id, name, enabled, priority, conditions, actions, created_at, updated_at from rules where id = $1 and user_id = $2
`

type GetRuleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, getRule, arg.ID, arg.UserID)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.Conditions,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRules = `-- name: ListRules :many
select id, user_id, name, enabled, priority, conditions, actions, created_at, updated_at from rules
where user_id = $1
order by priority, created_at
`

func (q *Queries) ListRules(ctx context.Context, userID uuid.UUID) ([]Rule, error) {
	rows, err := q.db.QueryContext(ctx, listRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.Conditions,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRule = `-- name: ToggleRule :exec
update rules
set enabled = not enabled, updated_at = now()
where id = $1 and user_id = $2
`

type ToggleRuleParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ToggleRule(ctx context.Context, arg ToggleRuleParams) error {
	_, err := q.db.ExecContext(ctx, toggleRule, arg.ID, arg.UserID)
	return err
}

const updateRule = `-- name: UpdateRule :one
update rules
set name = $3, conditions = $4, actions = $5, updated_at = now()
where id = $1 and user_id = $2
returning id, user_id, name, enabled, priority, conditions, actions, created_at, updated_at
`

type UpdateRuleParams struct {
	ID         uuid.UUID       `json:"id"`
	UserID     uuid.UUID       `json:"user_id"`
	Name       string          `json:"name"`
	Conditions json.RawMessage `json:"conditions"`
	Actions    json.RawMessage `json:"actions"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (Rule, error) {
	row := q.db.QueryRowContext(ctx, updateRule,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Conditions,
		arg.Actions,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.Conditions,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
