// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: segments.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteSegment = `-- name: DeleteSegment :exec
delete from segments where user_id = $1 and name = $2
`

type DeleteSegmentParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) DeleteSegment(ctx context.Context, arg DeleteSegmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteSegment, arg.UserID, arg.Name)
	return err
}

const listSegments = `-- name: ListSegments :many
select user_id, name, segment_id, created_at, updated_at from segments where user_id = $1 order by name
`

func (q *Queries) ListSegments(ctx context.Context, userID uuid.UUID) ([]Segment, error) {
	rows, err := q.db.QueryContext(ctx, listSegments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Segment
	for rows.Next() {
		var i Segment
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.SegmentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSegment = `-- name: UpsertSegment :exec
insert into segments (user_id, name, segment_id)
values ($1, $2, $3)
on conflict (user_id, name) do update
set segment_id = excluded.segment_id, updated_at = now()
`

type UpsertSegmentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Name      string    `json:"name"`
	SegmentID int64     `json:"segment_id"`
}

func (q *Queries) UpsertSegment(ctx context.Context, arg UpsertSegmentParams) error {
	_, err := q.db.ExecContext(ctx, upsertSegment, arg.UserID, arg.Name, arg.SegmentID)
	return err
}
