// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteUser = `-- name: DeleteUser :exec
delete from users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const ensureUser = `-- name: EnsureUser :one
insert into users (strava_athlete_id, name)
values ($1, $2)
on conflict (strava_athlete_id)
do update set name = excluded.name, updated_at = now()
returning id, strava_athlete_id, name, parkrun_id, created_at, updated_at
`

type EnsureUserParams struct {
	StravaAthleteID int64  `json:"strava_athlete_id"`
	Name            string `json:"name"`
}

func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, ensureUser, arg.StravaAthleteID, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StravaAthleteID,
		&i.Name,
		&i.ParkrunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParkrunID = `-- name: GetParkrunID :one
select coalesce(parkrun_id, '') from users where id = $1
`

func (q *Queries) GetParkrunID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getParkrunID, id)
	var parkrun_id string
	err := row.Scan(&parkrun_id)
	return parkrun_id, err
}

const getStravaToken = `-- name: GetStravaToken :one
select token from strava_credentials where user_id = $1
`

func (q *Queries) GetStravaToken(ctx context.Context, userID uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getStravaToken, userID)
	var token json.RawMessage
	err := row.Scan(&token)
	return token, err
}

const getUser = `-- name: GetUser :one
select id, strava_athlete_id, name, parkrun_id, created_at, updated_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.StravaAthleteID,
		&i.Name,
		&i.ParkrunID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setParkrunID = `-- name: SetParkrunID :exec
update users set parkrun_id = $2, updated_at = now() where id = $1
`

type SetParkrunIDParams struct {
	ID        uuid.UUID      `json:"id"`
	ParkrunID sql.NullString `json:"parkrun_id"`
}

func (q *Queries) SetParkrunID(ctx context.Context, arg SetParkrunIDParams) error {
	_, err := q.db.ExecContext(ctx, setParkrunID, arg.ID, arg.ParkrunID)
	return err
}

const setStravaToken = `-- name: SetStravaToken :exec
insert into strava_credentials (user_id, token)
values ($1, $2)
on conflict (user_id) do update set token = excluded.token, updated_at = now()
`

type SetStravaTokenParams struct {
	UserID uuid.UUID       `json:"user_id"`
	Token  json.RawMessage `json:"token"`
}

func (q *Queries) SetStravaToken(ctx context.Context, arg SetStravaTokenParams) error {
	_, err := q.db.ExecContext(ctx, setStravaToken, arg.UserID, arg.Token)
	return err
}

const userIDByAthlete = `-- name: UserIDByAthlete :one
select id from users where strava_athlete_id = $1
`

func (q *Queries) UserIDByAthlete(ctx context.Context, stravaAthleteID int64) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, userIDByAthlete, stravaAthleteID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
