// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vars.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteVar = `-- name: DeleteVar :exec
delete from vars where user_id = $1 and name = $2
`

type DeleteVarParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) DeleteVar(ctx context.Context, arg DeleteVarParams) error {
	_, err := q.db.ExecContext(ctx, deleteVar, arg.UserID, arg.Name)
	return err
}

const listVars = `-- name: ListVars :many
select user_id, name, type, value, created_at, updated_at from vars where user_id = $1 order by name
`

func (q *Queries) ListVars(ctx context.Context, userID uuid.UUID) ([]Var, error) {
	rows, err := q.db.QueryContext(ctx, listVars, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Var
	for rows.Next() {
		var i Var
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVar = `-- name: UpsertVar :exec
insert into vars (user_id, name, type, value)
values ($1, $2, $3, $4)
on conflict (user_id, name) do update
set type = excluded.type, value = excluded.value, updated_at = now()
`

type UpsertVarParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
	Type   string    `json:"type"`
	Value  string    `json:"value"`
}

func (q *Queries) UpsertVar(ctx context.Context, arg UpsertVarParams) error {
	_, err := q.db.ExecContext(ctx, upsertVar,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Value,
	)
	return err
}
