users:
  57192790:
    - type: challenge
      name: "Nedd's Uncomfortable Challenge"
      start: "20/10/2024"
      end: "29/10/2024"
      template: |-
        Nedd's Uncomfortable Challenge: Day {{.Day}}/10
        Distance: {{printf "%.1f" .Distance}}km
        Total Time: {{.Duration}}

    - type: challenge
      name: "Lake Biwa Cycle"
      start: "02/11/2025"
      end: "08/11/2025"
      types: ["Ride"]
      template: |-
        Lake Biwa Cycle: Day {{.Day}}
        Total Distance: {{printf "%.1f" .Distance}}km
        Total Time: {{.Duration}}

    - type: parkrun
      parkrunner_id: 6364752
      types: ["Run", "Walk"]
